version: "3.9"
services:
  zooKeeper:
    container_name: "zooKeeperServer"
    image: zookeeper
#    environment:
#      POSTGRES_USER: "user"
#      POSTGRES_PASSWORD: "user"
#      POSTGRES_DB: "postgres"
#      PGDATA: "var/lib/postgresql/data/pgdata"
#    volumes:
#      - ./initDB:/docker-entrypoint-initdb.d
#      - .:/var/lib/postgresql/data
#      - ./dumps:/dumps
    ports:
      - "2181:2181"
#    networks:
#      - postgres

#  pgadmin:
#    container_name: "pgAdminTesting"
#    image: dpage/pgadmin4:5.7
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "lalala@email.com"
#      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
#      PGADMIN_CONFIG_SERVER_MODE: "False"
#    volumes:
#      - ./pgAdminData:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - postgres
#
#networks:
#  postgres:
#    driver: bridge